### ISSUE TITLE
Error occurs in copy IPs

### ISSUE THREAD

**Issue by daruyanagi** [Lierrmm/C-IP#137]
![image](https://user-images.githubusercontent.com/1104827/69552254-7dbfc700-0fe1-11ea-9391-e89f66c13dc5.png)

I confirmed this error in  ipvis 1.2.0.0, Windows 10 1909.

**Comment by Lierrmm** [comment]
This issue should be fixed in the latest version [1.2.1](https://github.com/Lierrmm/C-IP/releases/tag/1.2.1)
